### PR TITLE
Some more cool `stuff` added

### PR DESCRIPTION
**Pull request by sandbox-alg**

### CODE REVIEW

**Review by xitonix — COMMENTED** [review]
Do this please

**Review by xitonix — CHANGES_REQUESTED** [review]
sdfsdf

**Review by xitonix — COMMENTED** [review]
dfgdfgdfg

**Review by xitonix — APPROVED** [review]
ghjghj

**Review by xitonix — COMMENTED** [review]
dfgdfg

**Review by xitonix — COMMENTED** [review]
ertert

**Review by xitonix — COMMENTED** [review]
sdfsdf

**Review by xitonix — COMMENTED** [review]
rtyrty

**Review by xitonix — COMMENTED** [review]
asdasd

**Review by xitonix — COMMENTED** [review]
sdfsdf

**Review by xitonix — APPROVED** [review]
sdfsdf

**Review by sandbox-alg — COMMENTED** [review]
ertert

**Review by xitonix — COMMENTED** [review]
ertert

**Review by sandbox-alg — COMMENTED** [review]
ertert

**Review by sandbox-alg — COMMENTED** [review]
sdfsdf

**Review by xitonix — COMMENTED** [review]
sdfsdf

**Review by xitonix — COMMENTED** [review]
sdfsdf

**Review by xitonix — CHANGES_REQUESTED** [review]
dfgdfg

**Review by xitonix — COMMENTED** [review]
werwer

**Review by xitonix — COMMENTED** [review]
ghjghj

**Review by xitonix — COMMENTED** [review]
tyutyuty

**Review by xitonix — COMMENTED** [review]
sdfsdf

**Review by xitonix — COMMENTED** [review]
werwer

**Review by xitonix — APPROVED** [review]
asdasd

**Pull request merged**
